import { motion } from "framer-motion";
import { Download, CheckCircle2, XCircle, Info } from "lucide-react";
import TrustGauge from "./TrustGauge";
import RiskBadge from "./RiskBadge";
import RiskDistributionChart from "./RiskDistributionChart";
import DetectionHistoryChart from "./DetectionHistoryChart";
import FrameAnalysisTimeline from "./FrameAnalysisTimeline";
import AudioSegmentsTimeline from "./AudioSegmentsTimeline";
import QualityMetricsCard from "./QualityMetricsCard";
import WarningsList from "./WarningsList";
import HeatmapPanel from "./HeatmapPanel";
import Button from "./Button";

function formatTimestamp(iso) {
  return new Date(iso).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function downloadReport(report) {
  const blob = new Blob([JSON.stringify(report, null, 2)], {
    type: "application/json",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `truelens-report-${report.file_name ?? "media"}.json`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

// Card entrance, per the motion spec: 250ms, translateY(12px -> 0px),
// opacity 0 -> 1, ease-out. Cards stagger in 80ms apart so the report
// reads as one fluid reveal instead of everything snapping in at once.
const listVariants = {
  hidden: {},
  show: { transition: { staggerChildren: 0.08 } },
};
const cardVariants = {
  hidden: { opacity: 0, y: 12 },
  show: { opacity: 1, y: 0, transition: { duration: 0.25, ease: "easeOut" } },
};

export default function ForensicsReportPanel({ report, history, demoMode = false }) {
  return (
    <motion.div
      variants={listVariants}
      initial="hidden"
      animate="show"
      className="space-y-5"
    >
      {demoMode && (
        <motion.div
          variants={cardVariants}
          className="flex items-center gap-2 rounded-control border border-warning/30 bg-warning/5 px-4 py-2.5 text-xs font-medium text-warning"
        >
          <Info size={14} className="shrink-0" />
          Demo mode — the forensics backend wasn't reachable, so this report
          was generated by the local demo simulator, not the live model.
        </motion.div>
      )}

      {/* Header */}
      <motion.div variants={cardVariants} className="rounded-card border border-border bg-white p-6 shadow-soft">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <p className="text-xs font-medium uppercase tracking-wide text-ink-secondary">
              Prediction
            </p>
            <h2 className="mt-1 font-display text-2xl font-bold text-ink">
              {report.prediction}
            </h2>
          </div>
          <RiskBadge level={report.risk_level} />
        </div>

        <div className="mt-6 flex justify-center border-t border-border pt-6">
          <TrustGauge score={report.deepfake_probability} size={148} />
        </div>

        <dl className="mt-6 grid grid-cols-2 gap-4 border-t border-border pt-5 text-sm sm:grid-cols-4">
          <div>
            <dt className="text-xs text-ink-secondary">Media type</dt>
            <dd className="mt-0.5 font-medium text-ink">{report.media_type}</dd>
          </div>
          <div>
            <dt className="text-xs text-ink-secondary">Processing time</dt>
            <dd className="mt-0.5 font-medium text-ink">
              {report.processing_time}
            </dd>
          </div>
          {report.confidence !== undefined && (
            <div>
              <dt className="text-xs text-ink-secondary">Confidence</dt>
              <dd className="mt-0.5 font-medium text-ink">{report.confidence}%</dd>
            </div>
          )}
          {report.face_detected !== undefined && (
            <div>
              <dt className="text-xs text-ink-secondary">Face detected</dt>
              <dd className="mt-0.5 font-medium text-ink">
                {report.face_detected ? "Yes" : "No"}
                {report.face_count > 1 ? ` (${report.face_count})` : ""}
              </dd>
            </div>
          )}
          {(report.frames_analyzed !== undefined || report.frame_analysis) && (
            <div>
              <dt className="text-xs text-ink-secondary">Frames analyzed</dt>
              <dd className="mt-0.5 font-medium text-ink">
                {report.frames_analyzed ?? report.frame_analysis?.frame_count_analyzed}
                {(report.frames_skipped ?? report.frame_analysis?.frames_skipped) > 0
                  ? ` (${report.frames_skipped ?? report.frame_analysis?.frames_skipped} skipped)`
                  : ""}
              </dd>
            </div>
          )}
          <div className={report.face_detected !== undefined ? "" : "col-span-2 sm:col-span-2"}>
            <dt className="text-xs text-ink-secondary">Analyzed</dt>
            <dd className="mt-0.5 font-medium text-ink">
              {formatTimestamp(report.timestamp)}
            </dd>
          </div>
        </dl>
      </motion.div>

      {/* Summary */}
      <motion.div variants={cardVariants} className="rounded-card border border-border bg-white p-6 shadow-soft">
        <h3 className="font-display text-base font-semibold text-ink">
          Analysis summary
        </h3>
        <p className="mt-2 text-sm leading-relaxed text-ink-secondary">
          {report.summary}
        </p>
      </motion.div>

      {/* Warnings (low quality input, model fallback, etc — no-ops if none) */}
      <motion.div variants={cardVariants}>
        <WarningsList warnings={report.warnings} />
      </motion.div>

      {/* Pipeline used + quality metrics (image/video; no-ops otherwise) */}
      <motion.div variants={cardVariants}>
        <QualityMetricsCard report={report} />
      </motion.div>

      {/* Grad-CAM explainability heatmap (image only; no-ops otherwise) */}
      <motion.div variants={cardVariants}>
        <HeatmapPanel heatmap={report.heatmap} overlay={report.heatmap_overlay} />
      </motion.div>

      {/* Frame-by-frame timeline (video only; no-ops otherwise) */}
      <motion.div variants={cardVariants}>
        <FrameAnalysisTimeline frameAnalysis={report.frame_analysis} />
      </motion.div>

      {/* Segment-by-segment timeline (audio only; no-ops otherwise) */}
      <motion.div variants={cardVariants}>
        <AudioSegmentsTimeline segments={report.segments} />
      </motion.div>

      {/* Visual indicators */}
      <motion.div variants={cardVariants} className="rounded-card border border-border bg-white p-6 shadow-soft">
        <div className="flex items-center justify-between">
          <h3 className="font-display text-base font-semibold text-ink">
            Indicators checked
          </h3>
          <span className="inline-flex items-center gap-1 rounded-full bg-surface-secondary px-2 py-0.5 text-[11px] font-medium text-ink-secondary">
            <Info size={11} /> Heuristic signals
          </span>
        </div>
        <ul className="mt-4 space-y-2.5">
          {report.visual_indicators.map((indicator) => (
            <li key={indicator.label} className="flex items-center gap-2.5 text-sm">
              {indicator.flagged ? (
                <XCircle size={16} className="shrink-0 text-danger" />
              ) : (
                <CheckCircle2 size={16} className="shrink-0 text-success" />
              )}
              <span className="text-ink">{indicator.label}</span>
              <span
                className={`ml-auto text-xs font-medium ${
                  indicator.flagged ? "text-danger" : "text-ink-secondary"
                }`}
              >
                {indicator.flagged ? "Flagged" : "Clear"}
              </span>
            </li>
          ))}
        </ul>
      </motion.div>

      {/* Recommendations */}
      <motion.div variants={cardVariants} className="rounded-card border border-border bg-white p-6 shadow-soft">
        <h3 className="font-display text-base font-semibold text-ink">
          Recommendations
        </h3>
        <ul className="mt-3 space-y-2">
          {report.recommendations.map((rec) => (
            <li key={rec} className="flex gap-2.5 text-sm text-ink-secondary">
              <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-accent-700" />
              {rec}
            </li>
          ))}
        </ul>
      </motion.div>

      {/* Session charts */}
      <motion.div variants={cardVariants} className="grid gap-5 sm:grid-cols-2">
        <div className="rounded-card border border-border bg-white p-6 shadow-soft">
          <h3 className="font-display text-sm font-semibold text-ink">
            Deepfake probability history
          </h3>
          <p className="mt-0.5 text-xs text-ink-secondary">
            This browser session, most recent 10
          </p>
          <div className="mt-2">
            <DetectionHistoryChart history={history} />
          </div>
        </div>
        <div className="rounded-card border border-border bg-white p-6 shadow-soft">
          <h3 className="font-display text-sm font-semibold text-ink">
            Risk distribution
          </h3>
          <p className="mt-0.5 text-xs text-ink-secondary">
            This browser session
          </p>
          <div className="mt-2">
            <RiskDistributionChart history={history} />
          </div>
        </div>
      </motion.div>

      <motion.div variants={cardVariants}>
        <Button
          variant="secondary"
          className="w-full justify-center"
          onClick={() => downloadReport(report)}
        >
          <Download size={15} /> Download report (JSON)
        </Button>
      </motion.div>
    </motion.div>
  );
}
